FROM php:apache
RUN apt update
RUN apt install -y libcurl4-openssl-dev libzip-dev zlib1g bzip2 libbz2-dev libpng-dev libjpeg-dev
RUN docker-php-ext-install mysqli curl zip bz2 gd
RUN a2enmod ssl
RUN a2enmod proxy
RUN a2enmod proxy_http
RUN a2enmod expires
RUN a2enmod rewrite

