version: "3.5"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: doh
    image: m13253/dns-over-https-server:latest
    environment:
      TZ: 'Europe/Paris'
    volumes:
      - '/etc/letsencrypt:/etc/letsencrypt'
      - '/opt/doh_storage/doh-server.conf:/doh-server.conf'
    ports:
      - 8053:8053
    hostname: doh
    networks:
      - network1
    restart: unless-stopped
    
networks:
  network1:
    name: docker_default
    external: true
