version: "3.5"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'Europe/Paris'
      VIRTUAL_HOST: 'pihole.ad.boorce.com'
      PROXY_LOCATION: 'pihole.ad.boorce.com'
      WEBPASSWORD: 'Haddock@01'
      ServerIP: '192.168.0.250'
      ServerIPv6: '2a01:e0a:508:d990:42:c0ff:fea8:fa'
    volumes:
      - '/opt/pihole_storage/etc-pihole:/etc/pihole/'
      - '/opt/pihole_storage/etc-dnsmasq.d:/etc/dnsmasq.d/'
      - '/var/lib/tftpboot:/var/lib/tftpboot/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    dns: 192.168.0.254
    hostname: dockerstar01
    networks:
      net_local:
        ipv4_address: 192.168.0.250
        ipv6_address: 2a01:e0a:508:d990:42:c0ff:fea8:fa
    restart: unless-stopped
    
networks:
  net_local:
    external: 
      name: net_local
