version: "3.5"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  mediamtx:
    container_name: mediamtx
    image: bluenviron/mediamtx:latest
    volumes:
      - '/etc/letsencrypt:/etc/letsencrypt'
      - '/opt/mediamtx_storage/mediamtx.yml:/mediamtx.yml'
    dns: 192.168.0.250
    ports:
      - 8889:8889
    environment:
      TS: 'Europe/Paris'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    hostname: mediamtx
    networks:    
      net_local:
        ipv4_address: 192.168.0.251
        ipv6_address: 2a01:e0a:809:d140:42:c0ff:fea8:fb

networks:
  net_local:
    external:
      name: net_local

